export const collegeBenchmarks = [
  {
    id: "stanford",
    name: "Stanford University",
    acceptanceRate: 4,
    gpaMinimum: 3.75,
    gpaCompetitive: 3.95,
    recommendedEcHours: 14,
    recommendedActivityCount: 4,
    focusTags: ["computer-science", "engineering", "entrepreneurship", "research", "design"],
  },
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    acceptanceRate: 4,
    gpaMinimum: 3.8,
    gpaCompetitive: 3.95,
    recommendedEcHours: 14,
    recommendedActivityCount: 4,
    focusTags: ["engineering", "computer-science", "research", "math", "physics"],
  },
  {
    id: "harvard",
    name: "Harvard University",
    acceptanceRate: 4,
    gpaMinimum: 3.8,
    gpaCompetitive: 3.95,
    recommendedEcHours: 14,
    recommendedActivityCount: 4,
    focusTags: ["leadership", "policy", "research", "business", "public-impact"],
  },
  {
    id: "princeton",
    name: "Princeton University",
    acceptanceRate: 5,
    gpaMinimum: 3.8,
    gpaCompetitive: 3.95,
    recommendedEcHours: 13,
    recommendedActivityCount: 4,
    focusTags: ["research", "policy", "math", "economics", "leadership"],
  },
  {
    id: "columbia",
    name: "Columbia University",
    acceptanceRate: 4,
    gpaMinimum: 3.75,
    gpaCompetitive: 3.9,
    recommendedEcHours: 12,
    recommendedActivityCount: 4,
    focusTags: ["research", "business", "policy", "journalism", "engineering"],
  },
  {
    id: "upenn",
    name: "University of Pennsylvania",
    acceptanceRate: 6,
    gpaMinimum: 3.75,
    gpaCompetitive: 3.9,
    recommendedEcHours: 12,
    recommendedActivityCount: 4,
    focusTags: ["business", "finance", "entrepreneurship", "research", "leadership"],
  },
  {
    id: "duke",
    name: "Duke University",
    acceptanceRate: 6,
    gpaMinimum: 3.7,
    gpaCompetitive: 3.9,
    recommendedEcHours: 12,
    recommendedActivityCount: 4,
    focusTags: ["biology", "medicine", "engineering", "leadership", "research"],
  },
  {
    id: "johns-hopkins",
    name: "Johns Hopkins University",
    acceptanceRate: 7,
    gpaMinimum: 3.7,
    gpaCompetitive: 3.9,
    recommendedEcHours: 12,
    recommendedActivityCount: 4,
    focusTags: ["biology", "medicine", "research", "public-health", "neuroscience"],
  },
  {
    id: "cmu",
    name: "Carnegie Mellon University",
    acceptanceRate: 11,
    gpaMinimum: 3.7,
    gpaCompetitive: 3.9,
    recommendedEcHours: 11,
    recommendedActivityCount: 3,
    focusTags: ["computer-science", "engineering", "design", "robotics", "research"],
  },
  {
    id: "berkeley",
    name: "UC Berkeley",
    acceptanceRate: 11,
    gpaMinimum: 3.65,
    gpaCompetitive: 3.85,
    recommendedEcHours: 10,
    recommendedActivityCount: 3,
    focusTags: ["computer-science", "engineering", "economics", "policy", "research"],
  },
  {
    id: "ucla",
    name: "UCLA",
    acceptanceRate: 9,
    gpaMinimum: 3.65,
    gpaCompetitive: 3.85,
    recommendedEcHours: 10,
    recommendedActivityCount: 3,
    focusTags: ["biology", "psychology", "design", "business", "research"],
  },
  {
    id: "ucsd",
    name: "UC San Diego",
    acceptanceRate: 24,
    gpaMinimum: 3.5,
    gpaCompetitive: 3.75,
    recommendedEcHours: 8,
    recommendedActivityCount: 3,
    focusTags: ["biology", "computer-science", "engineering", "public-health", "research"],
  },
  {
    id: "usc",
    name: "USC",
    acceptanceRate: 12,
    gpaMinimum: 3.6,
    gpaCompetitive: 3.8,
    recommendedEcHours: 10,
    recommendedActivityCount: 3,
    focusTags: ["business", "cinema", "engineering", "entrepreneurship", "design"],
  },
  {
    id: "nyu",
    name: "New York University",
    acceptanceRate: 13,
    gpaMinimum: 3.6,
    gpaCompetitive: 3.8,
    recommendedEcHours: 9,
    recommendedActivityCount: 3,
    focusTags: ["business", "finance", "media", "design", "data"],
  },
  {
    id: "northeastern",
    name: "Northeastern University",
    acceptanceRate: 7,
    gpaMinimum: 3.6,
    gpaCompetitive: 3.8,
    recommendedEcHours: 9,
    recommendedActivityCount: 3,
    focusTags: ["computer-science", "business", "co-op", "engineering", "data"],
  },
  {
    id: "umich",
    name: "University of Michigan",
    acceptanceRate: 18,
    gpaMinimum: 3.55,
    gpaCompetitive: 3.8,
    recommendedEcHours: 8,
    recommendedActivityCount: 3,
    focusTags: ["engineering", "business", "psychology", "public-policy", "research"],
  },
  {
    id: "georgia-tech",
    name: "Georgia Tech",
    acceptanceRate: 17,
    gpaMinimum: 3.55,
    gpaCompetitive: 3.8,
    recommendedEcHours: 9,
    recommendedActivityCount: 3,
    focusTags: ["engineering", "computer-science", "robotics", "math", "research"],
  },
  {
    id: "ut-austin",
    name: "UT Austin",
    acceptanceRate: 31,
    gpaMinimum: 3.5,
    gpaCompetitive: 3.75,
    recommendedEcHours: 8,
    recommendedActivityCount: 3,
    focusTags: ["business", "engineering", "computer-science", "policy", "entrepreneurship"],
  },
  {
    id: "purdue",
    name: "Purdue University",
    acceptanceRate: 53,
    gpaMinimum: 3.3,
    gpaCompetitive: 3.65,
    recommendedEcHours: 6,
    recommendedActivityCount: 2,
    focusTags: ["engineering", "computer-science", "aviation", "research", "innovation"],
  },
  {
    id: "uiuc",
    name: "University of Illinois Urbana-Champaign",
    acceptanceRate: 45,
    gpaMinimum: 3.45,
    gpaCompetitive: 3.75,
    recommendedEcHours: 7,
    recommendedActivityCount: 2,
    focusTags: ["engineering", "computer-science", "business", "data", "research"],
  },
  {
    id: "washington",
    name: "University of Washington",
    acceptanceRate: 48,
    gpaMinimum: 3.4,
    gpaCompetitive: 3.7,
    recommendedEcHours: 7,
    recommendedActivityCount: 2,
    focusTags: ["computer-science", "engineering", "public-health", "research", "biology"],
  },
  {
    id: "rutgers",
    name: "Rutgers University",
    acceptanceRate: 66,
    gpaMinimum: 3.2,
    gpaCompetitive: 3.55,
    recommendedEcHours: 5,
    recommendedActivityCount: 2,
    focusTags: ["biology", "pharmacy", "business", "psychology", "engineering"],
  },
];
