export const opportunities = [
  {
    id: "opp-001",
    title: "NASA App Development Challenge",
    category: "competition",
    tags: ["ai", "space", "coding", "data"],
    deadline: "2026-04-18",
    link: "https://www.nasa.gov/stem/murep/projects/",
    description: "Build a student-led software solution using NASA open datasets and present it to mission mentors.",
  },
  {
    id: "opp-002",
    title: "Google Summer of Code (Student Contributor)",
    category: "internship",
    tags: ["open-source", "coding", "ai", "systems"],
    deadline: "2026-04-20",
    link: "https://summerofcode.withgoogle.com/",
    description: "Contribute to major open-source projects under mentorship and ship production-grade features.",
  },
  {
    id: "opp-003",
    title: "MIT Blueprint Hackathon",
    category: "hackathon",
    tags: ["ai", "product", "social-impact", "web"],
    deadline: "2026-04-22",
    link: "https://blueprint.hackmit.org/",
    description: "Design and launch a civic-impact app with workshops, judging, and recruiter exposure.",
  },
  {
    id: "opp-004",
    title: "Regeneron Science Talent Search Prep Grant",
    category: "scholarship",
    tags: ["biology", "research", "science", "chemistry"],
    deadline: "2026-05-01",
    link: "https://www.societyforscience.org/regeneron-sts/",
    description: "Funding support for high school researchers preparing advanced STEM competition submissions.",
  },
  {
    id: "opp-005",
    title: "Meta University Engineering Program",
    category: "internship",
    tags: ["software", "web", "product", "business"],
    deadline: "2026-05-04",
    link: "https://www.metacareers.com/",
    description: "Early-career engineering internship for students interested in product-focused software development.",
  },
  {
    id: "opp-006",
    title: "PennApps",
    category: "hackathon",
    tags: ["coding", "startup", "ai", "design"],
    deadline: "2026-05-07",
    link: "https://pennapps.com/",
    description: "Launch a bold prototype over a weekend with top mentors, APIs, and sponsor prizes.",
  },
  {
    id: "opp-007",
    title: "Conrad Challenge Innovation Sprint",
    category: "competition",
    tags: ["business", "biotech", "ai", "entrepreneurship"],
    deadline: "2026-05-10",
    link: "https://www.conradchallenge.org/",
    description: "Student teams create market-ready innovations and pitch to industry leaders.",
  },
  {
    id: "opp-008",
    title: "Amazon Future Engineer Scholarship",
    category: "scholarship",
    tags: ["coding", "computer-science", "leadership", "equity"],
    deadline: "2026-05-12",
    link: "https://www.amazonfutureengineer.com/scholarship",
    description: "Scholarship plus internship pathway for students pursuing computer science careers.",
  },
  {
    id: "opp-009",
    title: "Stanford AI4ALL Summer Fellowship",
    category: "internship",
    tags: ["ai", "ethics", "research", "python"],
    deadline: "2026-05-15",
    link: "https://ai4all.org/",
    description: "Hands-on AI research experience focused on responsible deployment and practical project work.",
  },
  {
    id: "opp-010",
    title: "Hack the North",
    category: "hackathon",
    tags: ["coding", "ai", "cloud", "startup"],
    deadline: "2026-05-19",
    link: "https://hackthenorth.com/",
    description: "Compete in one of North America's flagship hackathons with sponsor mentoring and prizes.",
  },
  {
    id: "opp-011",
    title: "NSHSS STEM Scholarship",
    category: "scholarship",
    tags: ["science", "engineering", "research", "leadership"],
    deadline: "2026-05-25",
    link: "https://www.nshss.org/scholarships/",
    description: "Support for students pursuing ambitious STEM goals through academic and leadership projects.",
  },
  {
    id: "opp-012",
    title: "Girls Who Code Summer Immersion",
    category: "internship",
    tags: ["coding", "web", "community", "product"],
    deadline: "2026-05-30",
    link: "https://girlswhocode.com/programs/summer-immersion-program",
    description: "Build coding fluency with project-based learning and professional development coaching.",
  },
  {
    id: "opp-013",
    title: "BofA Student Leaders",
    category: "internship",
    tags: ["business", "leadership", "nonprofit", "policy"],
    deadline: "2026-06-01",
    link: "https://about.bankofamerica.com/en/making-an-impact/student-leaders",
    description: "Paid summer internship and leadership summit for civic-minded students.",
  },
  {
    id: "opp-014",
    title: "Breakthrough Junior Challenge",
    category: "competition",
    tags: ["video", "science", "physics", "communication"],
    deadline: "2026-06-05",
    link: "https://breakthroughjuniorchallenge.org/",
    description: "Create a compelling science explainer video and compete for scholarships and lab prizes.",
  },
  {
    id: "opp-015",
    title: "Code2040 Early Career Accelerator",
    category: "internship",
    tags: ["software", "career", "networking", "equity"],
    deadline: "2026-06-09",
    link: "https://www.code2040.org/",
    description: "Career accelerator connecting students with tech opportunities and mentorship.",
  },
  {
    id: "opp-016",
    title: "LaunchX High School Entrepreneurship Program",
    category: "competition",
    tags: ["startup", "business", "product", "marketing"],
    deadline: "2026-06-12",
    link: "https://www.launchx.com/",
    description: "Build a startup concept, validate users, and pitch to operators and investors.",
  },
  {
    id: "opp-017",
    title: "National Merit Scholarship Alternate Round",
    category: "scholarship",
    tags: ["academic", "leadership", "college", "merit"],
    deadline: "2026-06-15",
    link: "https://www.nationalmerit.org/",
    description: "Merit-based scholarship opportunity for top students with strong academics and leadership.",
  },
  {
    id: "opp-018",
    title: "AI Climate Hack",
    category: "hackathon",
    tags: ["ai", "climate", "data", "social-impact"],
    deadline: "2026-06-20",
    link: "https://www.climatehack.ai/",
    description: "Build climate-focused AI tools with real datasets and mentorship from domain experts.",
  },
  {
    id: "opp-019",
    title: "ISEF Regional Qualifier",
    category: "competition",
    tags: ["biology", "chemistry", "engineering", "research"],
    deadline: "2026-06-28",
    link: "https://www.societyforscience.org/isef/",
    description: "Present your original research project to judges and qualify for international science fairs.",
  },
  {
    id: "opp-020",
    title: "Prudential Emerging Visionaries",
    category: "scholarship",
    tags: ["social-impact", "leadership", "community", "nonprofit"],
    deadline: "2026-07-02",
    link: "https://www.prudential.com/links/emergingvisionaries",
    description: "Scholarship funding for students driving meaningful impact in their communities.",
  },
  {
    id: "opp-021",
    title: "Kaggle Student Data Science Challenge",
    category: "competition",
    tags: ["data", "ai", "machine-learning", "python"],
    deadline: "2026-07-07",
    link: "https://www.kaggle.com/competitions",
    description: "Compete on real ML problems and showcase your modeling skills on a public leaderboard.",
  },
  {
    id: "opp-022",
    title: "Figma Design for Education Jam",
    category: "hackathon",
    tags: ["design", "ux", "product", "education"],
    deadline: "2026-07-10",
    link: "https://www.figma.com/community",
    description: "Collaborative design sprint focused on building better student learning experiences.",
  },
  {
    id: "opp-023",
    title: "USACO Summer Training Camp",
    category: "competition",
    tags: ["algorithms", "coding", "math", "problem-solving"],
    deadline: "2026-07-14",
    link: "https://www.usaco.org/",
    description: "Advance competitive programming skills through elite-level algorithm training.",
  },
  {
    id: "opp-024",
    title: "NSF REU in Computational Biology",
    category: "internship",
    tags: ["biology", "coding", "research", "data"],
    deadline: "2026-07-19",
    link: "https://www.nsf.gov/crssprgm/reu/",
    description: "Research experience blending biology and computing in active university labs.",
  },
  {
    id: "opp-025",
    title: "DECA International Startup Event",
    category: "competition",
    tags: ["business", "finance", "marketing", "entrepreneurship"],
    deadline: "2026-07-24",
    link: "https://www.deca.org/",
    description: "Pitch a startup concept and compete in high-intensity business simulation rounds.",
  },
  {
    id: "opp-026",
    title: "Thiel Fellowship Prep Workshop",
    category: "competition",
    tags: ["startup", "deep-tech", "leadership", "product"],
    deadline: "2026-07-29",
    link: "https://thielfellowship.org/",
    description: "Coaching program for students exploring ambitious startup and innovation tracks.",
  },
  {
    id: "opp-027",
    title: "Apple Swift Student Challenge",
    category: "competition",
    tags: ["ios", "coding", "design", "product"],
    deadline: "2026-08-03",
    link: "https://developer.apple.com/swift-student-challenge/",
    description: "Build and submit a standout app playground demonstrating technical and creative skill.",
  },
  {
    id: "opp-028",
    title: "Google AI Scholars Scholarship",
    category: "scholarship",
    tags: ["ai", "machine-learning", "research", "education"],
    deadline: "2026-08-08",
    link: "https://ai.google/education/",
    description: "Funding for students pursuing AI-focused coursework, projects, and research goals.",
  },
  {
    id: "opp-029",
    title: "LaunchCode Software Apprenticeship",
    category: "internship",
    tags: ["coding", "career", "web", "backend"],
    deadline: "2026-08-12",
    link: "https://www.launchcode.org/",
    description: "Apprenticeship pathway pairing students with partner companies for practical coding work.",
  },
  {
    id: "opp-030",
    title: "World Series of Innovation",
    category: "competition",
    tags: ["entrepreneurship", "social-impact", "business", "sustainability"],
    deadline: "2026-08-16",
    link: "https://www.nfte.com/world-series-of-innovation/",
    description: "Solve global challenges through entrepreneurial ideas and validated execution plans.",
  },
  {
    id: "opp-031",
    title: "NASA Space Apps Local Edition",
    category: "hackathon",
    tags: ["space", "data", "coding", "science"],
    deadline: "2026-08-21",
    link: "https://www.spaceappschallenge.org/",
    description: "Collaborative global hackathon turning open data into creative space-tech solutions.",
  },
  {
    id: "opp-032",
    title: "Dell Scholars Program",
    category: "scholarship",
    tags: ["college", "leadership", "resilience", "community"],
    deadline: "2026-08-24",
    link: "https://www.dellscholars.org/students/",
    description: "Scholarship plus student support resources for high-achieving, driven learners.",
  },
  {
    id: "opp-033",
    title: "Stanford Pre-Collegiate Summer Institutes",
    category: "internship",
    tags: ["research", "business", "ai", "biomedical"],
    deadline: "2026-08-28",
    link: "https://summerinstitutes.spcs.stanford.edu/",
    description: "University-level coursework and project portfolio development for motivated students.",
  },
  {
    id: "opp-034",
    title: "MIT THINK Scholars",
    category: "scholarship",
    tags: ["research", "engineering", "science", "innovation"],
    deadline: "2026-09-03",
    link: "https://think.mit.edu/",
    description: "Receive mentorship and funding to execute your independent science research idea.",
  },
  {
    id: "opp-035",
    title: "CyberPatriot National Youth Challenge",
    category: "competition",
    tags: ["cybersecurity", "networking", "coding", "systems"],
    deadline: "2026-09-10",
    link: "https://www.uscyberpatriot.org/",
    description: "Defend virtual systems in a team competition and strengthen cybersecurity fundamentals.",
  },
  {
    id: "opp-036",
    title: "HackMIT",
    category: "hackathon",
    tags: ["ai", "product", "coding", "startup"],
    deadline: "2026-09-15",
    link: "https://hackmit.org/",
    description: "Flagship student hackathon with strong technical mentorship and launch-ready demos.",
  },
  {
    id: "opp-037",
    title: "Coca-Cola Scholars Program",
    category: "scholarship",
    tags: ["leadership", "service", "college", "community"],
    deadline: "2026-09-22",
    link: "https://www.coca-colascholarsfoundation.org/",
    description: "Prestige scholarship for high-impact students with strong academics and service records.",
  },
  {
    id: "opp-038",
    title: "Microsoft Discovery Program",
    category: "internship",
    tags: ["software", "product", "ai", "career"],
    deadline: "2026-10-01",
    link: "https://careers.microsoft.com/students/us/en",
    description: "Explore technical product development through guided projects and engineering mentorship.",
  },
  {
    id: "opp-039",
    title: "National Biology Olympiad Qualifier",
    category: "competition",
    tags: ["biology", "science", "research", "medicine"],
    deadline: "2026-10-10",
    link: "https://www.usabo-trc.org/",
    description: "Compete in advanced biology assessments and move toward national-level recognition.",
  },
  {
    id: "opp-040",
    title: "UNICEF Youth Climate Fellowship",
    category: "scholarship",
    tags: ["climate", "policy", "leadership", "social-impact"],
    deadline: "2026-10-20",
    link: "https://www.unicef.org/",
    description: "Fellowship support for youth leaders building impactful climate and policy initiatives.",
  },
];
